apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::899676604268:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-vPKLxLN1dqlG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::899676604268:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-30T03:00:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1414"
  uid: bbe2dd5a-285e-47a6-95a1-dd88eb2f7686
